import { getDb, admin } from './firebase.js';

const json = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } });
const cents = (n) => Math.round(Number(n || 0) * 100) / 100;
const WARRIOR_NAMES = ['Spartan','Leen','Thor','Ajax','Zara','Nero','Kira','Blade','Viper','Ghost','Storm','Raven','Atlas','Nova','Titan','Jade','Hawk','Blaze','Wolf','Echo','Dusk','Fang','Iron','Shadow','Pyro','Frost','Rex','Ash','Cruz','Thorn','Vale','Drake','Quinn','Rin','Skar','Nyx','Bolt','Ember','Cain','Lyra','Onyx','Sage','Flux','Dex','Vex','Knox','Aria','Zane','Mira','Hex'];
const STORY_SETS = [
{era:'Classic',events:[
{type:'kill',template:'{A} eliminated {B} with a surprise attack'},{type:'kill',template:'{A} stabbed {B} from behind'},{type:'kill',template:'{A} shot {B} with a poison arrow'},{type:'kill',template:'{A} strangled {B} in the dark'},{type:'kill',template:'{A} defeated {B} in hand-to-hand combat'},{type:'kill',template:'{A} pushed {B} off a cliff'},{type:'kill',template:'{A} set a trap that caught {B}'},{type:'kill',template:"{A} poisoned {B}'s water supply"},{type:'kill',template:'{A} outsmarted {B} and ended their run'},
{type:'env_death',template:'{B} fell into a pit and was eliminated'},{type:'env_death',template:'{B} was struck by lightning'},{type:'env_death',template:'{B} drowned crossing the river'},{type:'env_death',template:'{B} was crushed by a falling boulder'},{type:'env_death',template:"{B} ate poisonous berries and didn't survive"},{type:'env_death',template:'{B} got lost in the forest and never returned'},{type:'env_death',template:'{B} was ambushed by wild animals'},{type:'env_death',template:'{B} stepped on their own trap'},
{type:'powerup',template:'{A} found a med kit and fully recovered'},{type:'powerup',template:'{A} discovered a hidden weapons cache'},{type:'powerup',template:'{A} formed a temporary alliance with {B}'},{type:'powerup',template:'{A} found high ground and spotted everyone'},{type:'powerup',template:'{A} built a shelter and rested safely'},{type:'powerup',template:"{A} stole supplies from {B}'s camp while they slept"},{type:'betrayal',template:'{A} and {B} were allies — until {A} stabbed {B} in the back'},{type:'betrayal',template:'{A} pretended to help {B} then eliminated them'},{type:'near_miss',template:"{A} narrowly escaped {B}'s attack"},{type:'near_miss',template:'{A} survived an explosion with barely any health left'},{type:'near_miss',template:'{A} jumped over a pit that nearly claimed them'}]},
{era:'Jungle Survival',events:[
{type:'kill',template:'{A} used the canopy shadows to take down {B}'},{type:'kill',template:'{A} lured {B} into a vine snare'},{type:'kill',template:'{A} silenced {B} beside the waterfall'},{type:'kill',template:'{A} drove {B} out of cover and finished the fight'},{type:'kill',template:'{A} won a muddy riverbank duel against {B}'},{type:'betrayal',template:'{A} shared a campfire with {B}, then betrayed them at dawn'},{type:'betrayal',template:'{A} promised {B} safe passage through the reeds, then ended their run'},{type:'env_death',template:'{B} vanished in quicksand before anyone could help'},{type:'env_death',template:'{B} slipped from a rain-slick ridge and was eliminated'},{type:'env_death',template:'{B} disturbed a nest of venomous insects and fell'},{type:'env_death',template:'{B} was swept away by a flash flood'},{type:'powerup',template:'{A} found clean water and regained strength'},{type:'powerup',template:'{A} camouflaged their shelter with palm leaves'},{type:'powerup',template:'{A} followed animal tracks to a supply cache'},{type:'near_miss',template:'{A} ducked under a swinging log trap meant for {B}'},{type:'near_miss',template:'{A} escaped a jaguar by diving into the river'}]},
{era:'Urban Heist',events:[
{type:'kill',template:'{A} cornered {B} in an alley and eliminated them'},{type:'kill',template:'{A} used a rooftop ambush to defeat {B}'},{type:'kill',template:'{A} cut the lights and took out {B}'},{type:'kill',template:'{A} rammed through a barricade and ended {B}'},{type:'kill',template:'{A} won a stairwell brawl against {B}'},{type:'betrayal',template:'{A} split the loot with {B}, then left them behind'},{type:'betrayal',template:'{A} handed {B} a fake escape route and sprung the trap'},{type:'env_death',template:'{B} triggered a vault alarm trap and was eliminated'},{type:'env_death',template:'{B} fell through a broken skylight'},{type:'env_death',template:'{B} was pinned by a collapsing subway tunnel'},{type:'env_death',template:'{B} crashed through a weak fire escape'},{type:'powerup',template:'{A} cracked a locker and found armor'},{type:'powerup',template:'{A} hotwired a getaway car for better positioning'},{type:'powerup',template:'{A} hacked the camera grid and tracked {B}'},{type:'near_miss',template:'{A} rolled clear as {B} opened fire'},{type:'near_miss',template:'{A} escaped a rooftop chase with seconds to spare'}]},
{era:'Sci-Fi',events:[
{type:'kill',template:'{A} overloaded {B}\'s shield and eliminated them'},{type:'kill',template:'{A} landed a plasma shot that dropped {B}'},{type:'kill',template:'{A} hacked {B}\'s drone and turned it against them'},{type:'kill',template:'{A} vented the corridor and defeated {B}'},{type:'kill',template:'{A} won a zero-gravity duel against {B}'},{type:'betrayal',template:'{A} linked comms with {B}, then scrambled their suit controls'},{type:'betrayal',template:'{A} offered {B} oxygen, then stole the tank'},{type:'env_death',template:'{B} drifted into an ion storm and was eliminated'},{type:'env_death',template:'{B} ignored a radiation warning and collapsed'},{type:'env_death',template:'{B} was caught in an airlock malfunction'},{type:'env_death',template:'{B} stepped onto a failing grav-plate'},{type:'powerup',template:'{A} found an energy cell and recharged their gear'},{type:'powerup',template:'{A} activated a cloaking module'},{type:'powerup',template:'{A} scanned the arena from an orbital relay'},{type:'near_miss',template:'{A} blink-jumped away from {B}\'s plasma burst'},{type:'near_miss',template:'{A} sealed a cracked visor just in time'}]}];
function shuffle(a){ return [...a].sort(()=>Math.random()-0.5); }
function pickBotNames(count){ return shuffle(WARRIOR_NAMES).slice(0,count); }
function pickRandomEvent(actor,victim,set){ const ev=set.events[Math.floor(Math.random()*set.events.length)]; return { type:ev.type, text:ev.template.replaceAll('{A}',actor).replaceAll('{B}',victim) }; }
function weightedVictim(a,b,userChar,mode='paid'){ if(!['free','paid'].includes(mode)) return Math.random()<0.5?a:b; const bias=mode==='free'?0.67:0.89; if(a===userChar && b!==userChar) return Math.random()<bias ? a : b; if(b===userChar && a!==userChar) return Math.random()<bias ? b : a; return Math.random()<0.5?a:b; }
function simulateBattle(characters, opts={}){ let alive=[...characters]; const rounds=[]; let roundNum=1; const userChar=characters[0]; const mode=opts.mode||'paid'; const storySet=STORY_SETS[Math.floor(Math.random()*STORY_SETS.length)]; let userEliminatedRound=null, userFinishRank=1; while(alive.length>1&&roundNum<=50){ const roundEvents=[], toEliminate=[]; const maxEliminations=alive.length<=4?1:Math.floor(Math.random()*3)+1; let n=0; const shuffled=shuffle(alive); for(let i=0;i<shuffled.length&&n<maxEliminations;i++){ const a=shuffled[i], b=shuffled[(i+1)%shuffled.length]; const probe=storySet.events[Math.floor(Math.random()*storySet.events.length)]; let victim=null; if(probe.type==='kill'||probe.type==='betrayal') victim=weightedVictim(a,b,userChar,mode); else if(probe.type==='env_death') victim=a; const actor=victim===a?b:a; const event={type:probe.type,text:probe.template.replaceAll('{A}',actor).replaceAll('{B}',victim||b)}; roundEvents.push(event.text); if(victim&&!toEliminate.includes(victim)){ toEliminate.push(victim); if(victim===userChar){ userEliminatedRound=roundNum; userFinishRank=alive.length-toEliminate.length+1; roundEvents.push(`💀 ${userChar} was eliminated!`); } n++; } } if(toEliminate.length>1&&Math.random()<.10){ const revived=toEliminate.pop(); if(revived===userChar){ userEliminatedRound=null; userFinishRank=1; } roundEvents.push(`💊 ${revived} found a revival kit and returned to the battle!`); } alive=alive.filter(c=>!toEliminate.includes(c)); rounds.push({roundNum,era:storySet.era,events:roundEvents,eliminated:toEliminate,remaining:alive.length}); roundNum++; } return {rounds,winner:alive[0],userSurvived:alive[0]===userChar,era:storySet.era,userEliminatedRound,userFinishRank:alive[0]===userChar?1:userFinishRank}; }
function battlePointsForFinish(result){ if(result.userSurvived) return {points:20,desc:'Battle Royale — Champion finish'}; const rank=Number(result.userFinishRank||20); if(rank<=8) return {points:8,desc:'Battle Royale — Top 8 finish'}; return {points:3,desc:'Battle Royale — Played a round'}; }
async function sendBattleEmail(user,type,data){ const site=process.env.URL || process.env.DEPLOY_URL || ''; if(!site||!user?.email||!process.env.EMAIL_API_TOKEN) return; await fetch(`${site}/api/send-email`,{method:'POST',headers:{'Content-Type':'application/json','x-api-token':process.env.EMAIL_API_TOKEN},body:JSON.stringify({to:user.email,type,fromKey:'games',data})}).catch(()=>{}); }
async function notify(db,uid,msg){ await db.collection('userNotifs').add({uid,msg,read:false,createdAt:admin.firestore.FieldValue.serverTimestamp()}); }
async function createFreshBattleRoom(db){ await db.collection('battleRoyaleRooms').doc('current').set({mode:'multiplayer',status:'waiting',entryFee:2,maxPlayers:20,minPlayers:10,realPlayers:[],realPlayerCount:0,pot:0,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()}); }
async function settleBattleRoomById(roomId='current'){ const db=getDb(); const rr=db.collection('battleRoyaleRooms').doc(roomId); const rs=await rr.get(); if(!rs.exists) throw new Error('Room not found'); const room=rs.data()||{}; if(room.status==='completed') return room; const players=room.realPlayers||[]; if(players.length<Number(room.minPlayers||10)) throw new Error('Not enough players'); const chars=players.map(p=>p.userName); const result=simulateBattle(chars,{mode:'multiplayer'}); const winner=players.find(p=>p.userName===result.winner); if(!winner) throw new Error(`Battle winner did not match a real player: ${result.winner}`); const totalPot=cents(players.length*Number(room.entryFee||2)); const platformCut=Math.floor(totalPot*.15*100)/100; const winnerPayout=Math.floor(totalPot*.85*100)/100; const completed={...room,status:'completed',startedAt:admin.firestore.FieldValue.serverTimestamp(),completedAt:admin.firestore.FieldValue.serverTimestamp(),rounds:result.rounds,winner:result.winner,winnerUserId:winner.userId,winnerPayout,platformCut,era:result.era}; await db.runTransaction(async t=>{ const ur=db.collection('users').doc(winner.userId); t.update(ur,{'gameWallet.balance':admin.firestore.FieldValue.increment(winnerPayout),gameWalletBalance:admin.firestore.FieldValue.increment(winnerPayout),'gameWallet.totalWon':admin.firestore.FieldValue.increment(winnerPayout)}); t.set(db.collection('platformFees').doc(),{type:'battle_royale_multiplayer',amt:platformCut,roomId,createdAt:admin.firestore.FieldValue.serverTimestamp()}); t.set(db.collection('battleRoyaleRoomHistory').doc(roomId==='current'?`room-${Date.now()}`:roomId),completed); t.update(rr,completed); }); try { await Promise.allSettled(players.map(async p=>{ try { const userSnap=await db.collection('users').doc(p.userId).get(); const user=userSnap.data()||{}; const won=winner.userId===p.userId; await notify(db,p.userId,won?`👑 You won Battle Royale! $${winnerPayout.toFixed(2)} added to Game Wallet!`:`Better luck next time — ${result.winner} won Battle Royale!`); await sendBattleEmail(user, won?'battle_royale_win':'battle_royale_result', { payout: won?winnerPayout:0, winner: result.winner }); } catch(e){ console.error('battle room notification failed', roomId, p.userId, e); } })); } catch(e){ console.error('battle room notification block failed', roomId, e); } finally { await createFreshBattleRoom(db); } return {success:true,winner:result.winner,winnerUserId:winner.userId,winnerPayout,rounds:result.rounds,era:result.era}; }
export { getDb, admin, json, cents, pickBotNames, simulateBattle, battlePointsForFinish, notify, sendBattleEmail, createFreshBattleRoom, settleBattleRoomById };
