import { getDb, admin } from './firebase.js';

const json = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } });
const cents = (n) => Math.round(Number(n || 0) * 100) / 100;
const WARRIOR_NAMES = ['Spartan','Leen','Thor','Ajax','Zara','Nero','Kira','Blade','Viper','Ghost','Storm','Raven','Atlas','Nova','Titan','Jade','Hawk','Blaze','Wolf','Echo','Dusk','Fang','Iron','Shadow','Pyro','Frost','Rex','Ash','Cruz','Thorn','Vale','Drake','Quinn','Rin','Skar','Nyx','Bolt','Ember','Cain','Lyra','Onyx','Sage','Flux','Dex','Vex','Knox','Aria','Zane','Mira','Hex'];
const BATTLE_EVENTS = [
{type:'kill',template:'{A} eliminated {B} with a surprise attack'},{type:'kill',template:'{A} stabbed {B} from behind'},{type:'kill',template:'{A} shot {B} with a poison arrow'},{type:'kill',template:'{A} strangled {B} in the dark'},{type:'kill',template:'{A} defeated {B} in hand-to-hand combat'},{type:'kill',template:'{A} pushed {B} off a cliff'},{type:'kill',template:'{A} set a trap that caught {B}'},{type:'kill',template:"{A} poisoned {B}'s water supply"},{type:'kill',template:'{A} outsmarted {B} and ended their run'},
{type:'env_death',template:'{A} fell into a pit and was eliminated'},{type:'env_death',template:'{A} was struck by lightning'},{type:'env_death',template:'{A} drowned crossing the river'},{type:'env_death',template:'{A} was crushed by a falling boulder'},{type:'env_death',template:"{A} ate poisonous berries and didn't survive"},{type:'env_death',template:'{A} got lost in the forest and never returned'},{type:'env_death',template:'{A} died of laughter after tripping on a rock'},{type:'env_death',template:'{A} was ambushed by wild animals'},{type:'env_death',template:'{A} stepped on their own trap'},
{type:'powerup',template:'{A} found a med kit and fully recovered'},{type:'powerup',template:'{A} discovered a hidden weapons cache'},{type:'powerup',template:'{A} formed a temporary alliance with {B}'},{type:'powerup',template:'{A} found high ground and spotted everyone'},{type:'powerup',template:'{A} built a shelter and rested safely'},{type:'powerup',template:"{A} stole supplies from {B}'s camp while they slept"},
{type:'betrayal',template:'{A} and {B} were allies — until {A} stabbed {B} in the back'},{type:'betrayal',template:'{A} pretended to help {B} then eliminated them'},
{type:'near_miss',template:"{A} narrowly escaped {B}'s attack"},{type:'near_miss',template:'{A} survived an explosion with barely any health left'},{type:'near_miss',template:'{A} jumped over a pit that nearly claimed them'}];
function shuffle(a){ return [...a].sort(()=>Math.random()-0.5); }
function pickBotNames(count){ return shuffle(WARRIOR_NAMES).slice(0,count); }
function pickRandomEvent(a,b){ const ev=BATTLE_EVENTS[Math.floor(Math.random()*BATTLE_EVENTS.length)]; return { type:ev.type, text:ev.template.replaceAll('{A}',a).replaceAll('{B}',b), victim:b }; }
function weightedVictim(a,b,userChar){ if(a===userChar && b!==userChar) return Math.random()<0.89 ? a : b; if(b===userChar && a!==userChar) return Math.random()<0.89 ? b : a; return b; }
function simulateBattle(characters){ let alive=[...characters]; const rounds=[]; let roundNum=1; const userChar=characters[0]; while(alive.length>1&&roundNum<=50){ const roundEvents=[], toEliminate=[]; const maxEliminations=alive.length<=4?1:Math.floor(Math.random()*3)+1; let n=0; const shuffled=shuffle(alive); for(let i=0;i<shuffled.length&&n<maxEliminations;i++){ const a=shuffled[i], b=shuffled[(i+1)%shuffled.length]; const event=pickRandomEvent(a,b); let victim=null; if(event.type==='kill'||event.type==='betrayal') victim=weightedVictim(a,b,userChar); else if(event.type==='env_death') victim=a; roundEvents.push(event.text); if(victim&&!toEliminate.includes(victim)){ toEliminate.push(victim); n++; } } if(toEliminate.length>1&&Math.random()<.10){ const revived=toEliminate.pop(); roundEvents.push(`💊 ${revived} found a revival kit and returned to the battle!`); } alive=alive.filter(c=>!toEliminate.includes(c)); rounds.push({roundNum,events:roundEvents,eliminated:toEliminate,remaining:alive.length}); roundNum++; } return {rounds,winner:alive[0],userSurvived:alive[0]===userChar}; }
async function sendBattleEmail(user,type,data){ const site=process.env.URL || process.env.DEPLOY_URL || ''; if(!site||!user?.email||!process.env.EMAIL_API_TOKEN) return; await fetch(`${site}/.netlify/functions/send-email`,{method:'POST',headers:{'Content-Type':'application/json','x-api-token':process.env.EMAIL_API_TOKEN},body:JSON.stringify({to:user.email,type,fromKey:'games',data})}).catch(()=>{}); }
async function notify(db,uid,msg){ await db.collection('userNotifs').add({uid,msg,read:false,createdAt:admin.firestore.FieldValue.serverTimestamp()}); }
export { getDb, admin, json, cents, pickBotNames, simulateBattle, notify, sendBattleEmail };
